# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\projectcode\SNQT\init.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(397, 299)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 10, 311, 231))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.layoutMain = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.layoutMain.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.layoutMain.setContentsMargins(10, 10, 10, 10)
        self.layoutMain.setObjectName("layoutMain")
        self.PushGMY = PushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        self.PushGMY.setFont(font)
        self.PushGMY.setObjectName("PushGMY")
        self.layoutMain.addWidget(self.PushGMY)
        self.PushQM = PushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        self.PushQM.setFont(font)
        self.PushQM.setObjectName("PushQM")
        self.layoutMain.addWidget(self.PushQM)
        self.PushQuit = PushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        self.PushQuit.setFont(font)
        self.PushQuit.setObjectName("PushQuit")
        self.layoutMain.addWidget(self.PushQuit)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 397, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "数据处理"))
        self.PushGMY.setText(_translate("MainWindow", "过敏原数据转换"))
        self.PushQM.setText(_translate("MainWindow", "千麦数据查询"))
        self.PushQuit.setText(_translate("MainWindow", "退      出"))
from qfluentwidgets import PushButton
