# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\projectcode\SNQT\init.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from qfluentwidgets import PushButton

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(380, 299)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.PushGMY = PushButton(self.centralwidget)
        self.PushGMY.setGeometry(QtCore.QRect(90, 40, 181, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        self.PushGMY.setFont(font)
        self.PushGMY.setObjectName("PushGMY")
        self.PushQM = PushButton(self.centralwidget)
        self.PushQM.setGeometry(QtCore.QRect(90, 110, 181, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        self.PushQM.setFont(font)
        self.PushQM.setObjectName("PushQM")
        self.PushQuit = PushButton(self.centralwidget)
        self.PushQuit.setGeometry(QtCore.QRect(90, 180, 181, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        self.PushQuit.setFont(font)
        self.PushQuit.setObjectName("PushQuit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 380, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "数据处理"))
        self.PushGMY.setText(_translate("MainWindow", "过敏原数据转换"))
        self.PushQM.setText(_translate("MainWindow", "千麦数据查询"))
        self.PushQuit.setText(_translate("MainWindow", "退      出"))

